# Generated by Django 3.1.5 on 2021-02-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafixturecolumn',
            options={'ordering': ['order']},
        ),
    ]
