# Generated by Django 3.1.5 on 2021-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0003_dataset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(max_length=25),
        ),
    ]
